### PR TITLE
Support configurable CRS in WCS services

### LINKED ISSUE #305: Enable a configuration of supported projections for WCS
The OGC WCS specifications 1.1.1 mentions that CoverageSummary elements in GetCapibilities response can include multiple supported Coordinate Reference System (Table 4). Currently, GeoTrellis-Server has no configuration capability available to define additional CRS that the default ones, WGS84, WebMercator and the native projection.
The expected behaviour would be to enable a configuration parameter such as the one available on the WMS configuration through the parameter supported-projections allowing to define a list of supported CRS. This additional parameter could be enable at the Service level or at the Layer level.

### PR DESCRIPTION
**Pull request by jisantuc**
## Overview

This PR adds a `supportedProjections` attribute to the `WcsConf` case class, adds example configuration to the `stac-example` and `ogc-example` projects, and consumes those supported projections when rendering the `GetCapabilities` response.

### Checklist

- [x] Description of PR is in an appropriate section of the CHANGELOG and grouped with similar changes if possible

### Demo

```bash
$ http :9000 service==wcs request==getcapabilities
HTTP/1.1 200 OK
Content-Length: 8925
Content-Type: application/xml
Date: Tue, 16 Feb 2021 16:46:01 GMT

...
<CoverageSummary>
  <ows:Title>US NED</ows:Title>
  <ows:WGS84BoundingBox>
    <ows:LowerCorner>-15.015761449275047 -171.00056648254395</ows:LowerCorner>
    <ows:UpperCorner>72.00056298703436 164.00399450196636</ows:UpperCorner>
  </ows:WGS84BoundingBox>
  <SupportedCRS>urn:ogc:def:crs:OGC::imageCRS</SupportedCRS>
  <SupportedCRS>urn:ogc:def:crs:EPSG::3785</SupportedCRS>
  <SupportedCRS>urn:ogc:def:crs:EPSG::4326</SupportedCRS>
  <SupportedCRS>urn:ogc:def:crs:EPSG::3410</SupportedCRS>
  <SupportedCRS>urn:ogc:def:crs:EPSG::3978</SupportedCRS>
  <SupportedCRS>urn:ogc:def:crs:EPSG::4617</SupportedCRS>
  <SupportedCRS>urn:ogc:def:crs:EPSG::3979</SupportedCRS>
  <SupportedCRS>urn:ogc:def:crs:EPSG::3413</SupportedCRS>
  <SupportedCRS>urn:ogc:def:crs:EPSG::26916</SupportedCRS>
  <SupportedFormat>image/geotiff</SupportedFormat>
  <SupportedFormat>image/jpeg</SupportedFormat>
  <SupportedFormat>image/png</SupportedFormat>
  <Identifier>us-ned</Identifier>
</CoverageSummary>
...
```

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

- make the demo request with the ogc-example project running
- confirm you also see the CRSes that match the values from the `application.conf`
- optional: change those values and verify the server respects your changes

Closes #305

### CODE REVIEW

**Review by pomadchin — CHANGES_REQUESTED** [review]
Great! Could you also push these changes into the [WCS DescribeCoverage](https://github.com/geotrellis/geotrellis-server/blob/develop/ogc/src/main/scala/geotrellis/server/ogc/wcs/CoverageView.scala#L202-L205) request? 

The request example: `http://localhost:9000/?service=WCS&request=DescribeCoverage&identifiers=us-ned`

**Comment by jisantuc** [comment]
d4e2829 does the `DescribeCoverage` change -- it wasn't clear to me that the bboxes needed to include all the CRSes as well, since the wms getCapabilities response doesn't include it and the methods for bbox reprojection don't seem to be called anywhere (`bboxIn` on the two OGCSources I mean). Let me know if that read is incorrect.

**Comment by pomadchin** [comment]
@jisantuc I think the main goal of the `GetDescribeCoverage` to make the service comaptible with tools like QGIS. I think QGIS is pretty happy without having all projections listed in the `GetCoverage`, but (accroding to specs) we still need to list all projections supported by the coverage.

**Review by pomadchin — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
